api/urls.py
from django.urls import path
import os


from api.views import AdServe,AdServePopup
from dsp.urls import router2

# router2
urlpatterns = [
    path('ads/serve', AdServe.as_view(), name='ads_serve'),
    path('popup-ads/serve', AdServePopup.as_view(), name='ads_popup_serve'),
]
# if not os.name == 'nt':

dsp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router2 = DefaultRouter()
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.dashboard.urls')),
    path('accounts/', include('apps.accounts.urls')),
    path('api/v1/', include(router.urls)),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

apps/accounts/models.py
import uuid

from django.contrib.auth.models import User, Group
from django.db import models
from datetime import date,timedelta
# Create your models here.
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import datetime

from apps.helpers.models import TimeStamp, OperatorStamp
from apps.helpers.utils import CAMPAIGN_TYPE, STATUS_TYPE, INVOICE_STATUS, VISIT_TYPE, LIFE_STYLE, HEALTH_PPROBLEM, \
    ANC_TYPE, DELIVERY_CENTER, PregnancyCycle_TYPE, DELIVERY_TYPE, BIRTH_TYPE


class CompanyType(TimeStamp, OperatorStamp):
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return str(self.name)


class Company(TimeStamp, OperatorStamp):
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='institute', null=True, blank=True)
    type = models.ForeignKey(CompanyType, null=True, blank=True, on_delete=models.SET_NULL)
    code = models.CharField(max_length=30, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    website = models.URLField(null=True, blank=True)
    phone = models.CharField(max_length=20, null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    status = models.IntegerField(default=0, choices=STATUS_TYPE)
    cpm = models.DecimalField(max_digits=19, decimal_places=4, null=True, blank=True)

    def __str__(self):
        return str(self.name)


@receiver(post_save, sender=Company)
def update_code(sender, instance, **kwargs):
    if not instance.code:
        instance.code = 'C-' + str(1000 + instance.pk)
        post_save.disconnect(update_code, sender=Company)
        instance.save()
        post_save.connect(update_code, sender=Company)


class GroupProfile(TimeStamp, OperatorStamp):
    name = models.OneToOneField(Group, on_delete=models.CASCADE, null=True, blank=True)
    can_view_dashboard = models.BooleanField(default=False)
    # can_see_all_application = models.BooleanField(default=False)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    campaigns = models.JSONField(default=list,null=True,blank=True)

    def __str__(self):
        return self.name.name


#
# @receiver(post_save, sender=Group)
# def create_group_profile(sender, instance, **kwargs):
#     try:
#         GroupProfile.objects.create(name=instance)
#         # post_save.disconnect(update_code, sender=Group)
#         # instance.save()
#         # post_save.connect(update_code, sender=Group)
#     except:
#         pass
class Zilla(TimeStamp, OperatorStamp):
    zilla = models.CharField(max_length=255)

    def __str__(self):
        return str(self.zilla)

class Upazila(TimeStamp, OperatorStamp):
    upazila = models.CharField(max_length=255)
    zilla = models.ForeignKey(Zilla, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return str(self.upazila)

class Union(TimeStamp, OperatorStamp):
    union = models.CharField(max_length=255)
    upazila = models.ForeignKey(Upazila, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return str(self.union)

class Ward(TimeStamp, OperatorStamp):
    ward = models.CharField(max_length=255)
    union = models.ForeignKey(Union, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return str(self.ward)

class Profile(TimeStamp, OperatorStamp):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, blank=True, null=True)
    avatar = models.ImageField(null=True, blank=True)
    mobile = models.CharField(max_length=15, null=True, blank=True)
    ward = models.ForeignKey(Ward, on_delete=models.SET_NULL, null=True, blank=True)
    union = models.ForeignKey(Union, on_delete=models.SET_NULL, null=True, blank=True)
    upazila = models.ForeignKey(Upazila, on_delete=models.SET_NULL, null=True, blank=True)
    zilla = models.ForeignKey(Zilla, on_delete=models.SET_NULL, null=True, blank=True)
    # company = models.CharField(max_length=255, null=True, blank=True)
    location = models.CharField(max_length=255, null=True, blank=True, default='')


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, **kwargs):
    try:
        Profile.objects.create(user=instance)
        # post_save.disconnect(update_code, sender=Group)
        # instance.save()
        # post_save.connect(update_code, sender=Group)
    except:
        pass


INVENTORY_TYPE = (
    (1, 'Website'),
    (2, 'Android App'),
    (3, 'iOS App'),
)


class Staff(TimeStamp, OperatorStamp):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.EmailField(null=True, blank=True)
    phone = models.CharField(max_length=20, null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    status = models.IntegerField(default=0, choices=STATUS_TYPE)
    joining_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return str(self.first_name)



class Patient(TimeStamp, OperatorStamp):
    agency = models.ForeignKey('accounts.Company', related_name='+', on_delete=models.SET_NULL, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    registration_no = models.CharField(max_length=255, null=True, blank=True)
    patient_name = models.CharField(max_length=255, null=True, blank=True)
    husband_name = models.CharField(max_length=255, null=True, blank=True)
    patient_phone = models.CharField(max_length=20, null=True, blank=True)
    husband_phone = models.CharField(max_length=20, null=True, blank=True)
    couple_number = models.IntegerField(default=0, null=True, blank=True)
    nid_number = models.IntegerField(default=0, null=True, blank=True)
    road = models.TextField(null=True, blank=True)
    ward = models.ForeignKey(Ward, on_delete=models.SET_NULL, null=True, blank=True)
    union = models.ForeignKey(Union, on_delete=models.SET_NULL, null=True, blank=True)
    upazila = models.ForeignKey(Upazila, on_delete=models.SET_NULL, null=True, blank=True)
    zilla = models.ForeignKey(Zilla, on_delete=models.SET_NULL, null=True, blank=True)
    patient_age = models.DateField(null=True, blank=True)
    husband_age = models.DateField(null=True, blank=True)
    patient_blood_group = models.CharField(max_length=20, null=True, blank=True)
    husband_blood_group = models.CharField(max_length=20, null=True, blank=True)
    status = models.IntegerField(default=0, choices=STATUS_TYPE)

    def __str__(self):
        return str(self.patient_name)

    # def save(self, *args, **kwargs):
    #     # Check if patient_age is less than 18 or more than 35
    #     if self.patient_age:
    #         age = (date.today() - self.patient_age) // timedelta(days=365)
    #         if age < 18 or age > 35:
    #             self.patient_status = 1
    #
    #     # Check if life_style or health_problem have values
    #     if self.life_style or self.health_problem:
    #         self.patient_status = 1
    #
    #     # Save patient_status based on conditions
    #     if not self.patient_status:
    #         self.patient_status = 0
    #
    #     creating = self.pk is None
    #     super().save(*args, **kwargs)
    #
    #     if creating and self.lmp:  # Check if lmp date is provided
    #         # Calculate appointment dates
    #         appointment_dates = [
    #             self.lmp + timedelta(days=120),  # One month plus
    #             self.lmp + timedelta(days=150),  # Two months plus
    #             self.lmp + timedelta(days=210)  # Three months plus
    #         ]
    #         anc_type_counter = 1
    #         # Create appointments
    #         for appointment_date in appointment_dates:
    #             Appointment.objects.create(
    #                 patient=self,
    #                 next_appointment_date=appointment_date,
    #                 agency=self.agency,
    #                 anc_type=anc_type_counter
    #
    #             )
    #             anc_type_counter += 1

class PregnancyCycle(TimeStamp, OperatorStamp):
    patient = models.ForeignKey(Patient, on_delete=models.SET_NULL, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    agency = models.ForeignKey('accounts.Company', related_name='+', on_delete=models.SET_NULL, blank=True, null=True)
    period_off_time = models.CharField(max_length=20, null=True, blank=True)
    pregnancy_number = models.IntegerField(max_length=20, null=True, blank=True)
    alive_children_number = models.IntegerField(max_length=20, null=True, blank=True)
    last_children_age = models.IntegerField(max_length=20, null=True, blank=True)
    normal_delivery_number = models.IntegerField(max_length=20, null=True, blank=True)
    csec_delivery_number = models.IntegerField(max_length=20, null=True, blank=True)
    mr_number = models.IntegerField(max_length=20, null=True, blank=True)
    monthly_income = models.IntegerField(max_length=20, null=True, blank=True)
    delivery_center = models.CharField(max_length=20, choices=DELIVERY_CENTER, null=True, blank=True)
    tt_dose_number = models.IntegerField(max_length=20, null=True, blank=True)
    after_delivery_plan = models.CharField(max_length=255, null=True, blank=True)
    assist_in_childbirth = models.CharField(max_length=255, null=True, blank=True)
    complications = models.CharField(max_length=255, null=True, blank=True)
    lmp = models.DateField(null=True, blank=True)
    edd = models.DateField(null=True, blank=True)
    delivery_complete_date = models.DateField(null=True, blank=True)
    life_style = models.JSONField(default=list, null=True, blank=True)
    health_problem = models.JSONField(default=list, null=True, blank=True)

apps/helpers/models.py
import uuid

from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from apps.helpers.utils import STATUS_TYPE


class OperatorStamp(models.Model):
    created_by = models.ForeignKey(User, related_name='+', on_delete=models.SET_NULL, blank=True, null=True)
    updated_by = models.ForeignKey(User, related_name='+', on_delete=models.SET_NULL, blank=True, null=True)

    class Meta:
        abstract = True


class TimeStamp(models.Model):
    created_at = models.DateTimeField(auto_now=False, auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, auto_now_add=False, blank=True, null=True)

    class Meta:
        abstract = True


class CommonModel(models.Model):
    uuid = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.IntegerField(choices=STATUS_TYPE, default=0)

    class Meta:
        abstract = True


class WithCreatorCommonModel(CommonModel):
    created_by = models.ForeignKey(User, related_name='+', on_delete=models.SET_NULL, blank=True, null=True)
    updated_by = models.ForeignKey(User, related_name='+', on_delete=models.SET_NULL, blank=True, null=True)

    class Meta:
        abstract = True

templates/vuexy/campaign/campaign/create.html
{% load crispy_forms_tags %}
<div class="text-center mb-4">
    <h3 class="role-title mb-2">Campaign Create Form</h3>
    <p class="text-muted">Set campaign data</p>
</div>
{% crispy form %}

templates/vuexy/campaign/campaign/detail.html
{% load campaign_tags %}
<div class="text-center mb-4">
    <h3 class="role-title mb-2">Campaign Detail</h3>
    {#    <p class="text-muted">Set group campaign data</p>#}
</div>

<div class="nav-align-top nav-tabs-shadow mb-4">
    <ul class="nav nav-tabs nav-fill" role="tablist">
        <li class="nav-item">
            <button
                    type="button"
                    class="nav-link active"
                    role="tab"
                    data-bs-toggle="tab"
                    data-bs-target="#navs-justified-info"
                    aria-controls="navs-justified-home"
                    aria-selected="true">
                <i class="tf-icons ti ti-home ti-xs me-1"></i> Info
                <span class="badge rounded-pill badge-center h-px-20 w-px-20 bg-label-danger ms-1">3</span>
            </button>
        </li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane fade show active" id="navs-justified-info" role="tabpanel">
            <p class="mb-0">
            <table class="table">
                <tbody>
                <tr data-dt-row="0" data-dt-column="1">
                    <td>Name:</td>
                    <td>{{ object.name }}</td>
                </tr>
                <tr data-dt-row="0" data-dt-column="2">
                    <td>Code:</td>
                    <td>{{ object.code }}</td>
                </tr>
                <tr data-dt-row="0" data-dt-column="5">
                    <td>Agency:</td>
                    <td>{{ object.agency }}</td>
                </tr>
                <tr data-dt-row="0" data-dt-column="5">
                    <td>Platform:</td>
                    <td>{{ object.platform }}</td>
                </tr>
                <tr data-dt-row="0" data-dt-column="5">
                    <td>Campaign Type:</td>
                    <td>{{ object.campaign_type }}</td>
                </tr>
                <tr data-dt-row="0" data-dt-column="7">
                    <td>Start Date:</td>
                    <td>{{ object.start_date }}</td>
                </tr>
                <tr data-dt-row="0" data-dt-column="7">
                    <td>End Date:</td>
                    <td>{{ object.end_date }}</td>
                </tr>
                </tbody>
            </table>
            </p>
            <div class="d-flex justify-content-end">
                <a href="javascript:;" data-url="/campaign/{{ object.id }}/edit"
                   class="btn btn-sm btn-success user-edit"
                   data-id="{{ object.id }}"><i class="ti ti-pencil ti-sm me-2"></i></a>
            </div>
        </div>
        <div class="tab-pane fade" id="navs-justified-inventory" role="tabpanel">
            <p class="mb-0">
            <table class="table">
                <tbody>

                <tr data-dt-row="0" data-dt-column="1">
                    <td>Frequency Capping:</td>
                    <td>{{ object.campaigninventory.frequency_capping }}</td>
                </tr>
                {% if object.campaigninventory.frequency_capping %}
                    <tr data-dt-row="0" data-dt-column="1">
                        <td>Capping Per Day:</td>
                        <td>{{ object.campaigninventory.capping_per_day }}</td>
                    </tr>
                {% endif %}
                <tr data-dt-row="0" data-dt-column="1">
                    <td>Rewarded Inventory:</td>
                    <td>{{ object.campaigninventory.is_rewarded_inventory }}</td>
                </tr>
                <tr data-dt-row="0" data-dt-column="1">
                    <td>Deal Package:</td>
                    <td>{{ object.campaigninventory.is_pmp }}</td>
                </tr>
                <tr data-dt-row="0" data-dt-column="1">
                    <td>Day Parting:</td>
                    <td>{{ object.campaigninventory.date_parting }}</td>
                </tr>
                <tr data-dt-row="0" data-dt-column="1">
                    <td>Open Publisher:</td>
                    <td>{{ object.campaigninventory.open_publisher }}</td>
                </tr>
                {% if not object.campaigninventory.open_publisher %}
                    <tr data-dt-row="0" data-dt-column="1">
                        <td>Sites:</td>
                        <td>{{ object.campaigninventory.sites | get_tag_from_list_of_dict | safe }}</td>
                    </tr>
                    <tr data-dt-row="0" data-dt-column="1">
                        <td>Apps:</td>
                        <td>{{ object.campaigninventory.apps | get_tag_from_list_of_dict | safe }}</td>
                    </tr>
                {% endif %}

                </tbody>
            </table>
            </p>
            <div class="d-flex justify-content-end">
                <a href="javascript:;" data-url="/campaign/inventory/{{ object.id }}/edit"
                   class="btn btn-sm btn-success user-edit"
                   data-id="{{ object.id }}"><i class="ti ti-pencil ti-sm me-2"></i></a>
            </div>
        </div>
        <div class="tab-pane fade" id="navs-justified-targets" role="tabpanel">
            <p class="mb-0">
            <table class="table">
                <tbody>
                <tr data-dt-row="0" data-dt-column="1">
                    <td>URL:</td>
                    <td>{{ object.campaigntargets.url }}</td>
                </tr>
                <tr data-dt-row="0" data-dt-column="1" class="border-bottom-primary">
                    <td>Landing URL:</td>
                    <td>{{ object.campaigntargets.landing_url }}</td>
                </tr>
                <hr/>
                <tr data-dt-row="0" data-dt-column="1">
                    <td>Billing ID:</td>
                    <td>{{ object.campaigntargets.billing_id }}</td>
                </tr>
                <tr data-dt-row="0" data-dt-column="1" class="border-bottom-primary">
                    <td>Deal ID:</td>
                    <td>{{ object.campaigntargets.deal_id }}</td>
                </tr>
                <tr data-dt-row="0" data-dt-column="1">
                    <td>From Hour:</td>
                    <td>{{ object.campaigntargets.from_hour }}</td>
                </tr>
                <tr data-dt-row="0" data-dt-column="1">
                    <td>To Hour:</td>
                    <td>{{ object.campaigntargets.to_hour }}</td>
                </tr>


                </tbody>
            </table>
            </p>
            <div class="d-flex justify-content-end">
                <a href="javascript:;" data-url="/campaign/targets/{{ object.id }}/edit"
                   class="btn btn-sm btn-success user-edit"
                   data-id="{{ object.id }}"><i class="ti ti-pencil ti-sm me-2"></i></a>
            </div>
        </div>
        <div class="tab-pane fade" id="navs-justified-creatives" role="tabpanel">
            <p class="mb-0">
            <table class="table">
                <thead>
                <tr>
                    <th>Creative</th>
                    <th>Dimension</th>
                    <th>Type</th>
                    <th>Status</th>
                    <th>Approval Status</th>
                </tr>
                </thead>
                <tbody>
                {% for creative in object.campaign_creatives.all %}
                    <tr>
                        <td>
                            <div class="creative_view">
                                {% if creative.type == 1 %}
                                    <img src="{{ creative.file.url }}" style="width: 100%" alt="">
                                {% elif creative.type == 101 %}
                                    {{ creative.html_tag | safe }}
                                {% elif creative.type == 301 %}
                                    <video src="{{ creative.file.url }}" style="width: 100%" controls></video>
                                {% endif %}
                                <div class="overlay">
                                    <a href="#" class="icon fullscreen" title="User Profile">
                                        <i class="fa fa-search-plus" aria-hidden="true"></i>
                                    </a>
                                </div>
                            </div>

                        </td>
                        <td>{{ creative.dimension }}</td>
                        <td>{{ creative.get_type_display }}</td>
                        <td>{{ creative.get_status_display }}</td>
                        <td>
{#                            <button type="button"#}
{#                                    class="btn btn-info">{{ creative.get_approval_status_display }}</button>#}
                            <select name="approval_status" data-id="{{ creative.id }}" class="approval_status">
                                <option value="0" {% if creative.approval_status == 0 %}selected{% endif %}>Pending</option>
                                <option value="1" {% if creative.approval_status == 1 %}selected{% endif %}>Approved</option>
                                <option value="2" {% if creative.approval_status == 2 %}selected{% endif %}>Rejected</option>
                            </select>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            </p>
            <div class="d-flex justify-content-end">
                <a href="javascript:;" data-url="/campaign/creative/{{ object.id }}/create"
                   class="btn btn-sm btn-success user-edit"
                   data-id="{{ object.id }}"><i class="ti ti-plus ti-sm me-2"></i> New Creative</a>
            </div>
        </div>
    </div>
</div>

templates/vuexy/campaign/campaign/edit.html
{% load crispy_forms_tags %}
<div class="text-center mb-4">
    <h3 class="role-title mb-2">Campaign Edit Form</h3>
    <p class="text-muted">Set campaign data</p>
</div>
{% crispy form %}